@host = https://localhost:7143

### Get All Railcar Trips
GET {{host}}/api/railcar-trips

Accept: application/json

###
# Get Trip Events by Trip ID
GET {{host}}/api/railcar-trips/1/events
Accept: application/json

### Get All Event Code Definitions
GET {{host}}/api/railcar-trips/event-codes

Accept: application/json


